# Generated by .github/render-formula.py during release. Do not edit by hand.
#
#   brew tap grahambrooks/increment https://github.com/grahambrooks/increment
#   brew install increment
class Increment < Formula
  desc "Diff visualizer for the terminal: the aligned side-by-side view"
  homepage "https://github.com/grahambrooks/increment"
  version "2026.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/increment/releases/download/v2026.8.0/increment-v2026.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "762c2dcf53053701be5d243684db6d17cd5dadc280912f22f531314fb0a7e7d6"
    elsif Hardware::CPU.intel?
      url "https://github.com/grahambrooks/increment/releases/download/v2026.8.0/increment-v2026.8.0-x86_64-apple-darwin.tar.gz"
      sha256 "e1b4accd82bc6c0477425a8817ca8ae4748ca2d5b02e0d83f19738cb8c608dd9"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/increment/releases/download/v2026.8.0/increment-v2026.8.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "28f170ee5a1fc6560399f8ad4a161ee45816a1c2df7905b9497a651a519dd85c"
    elsif Hardware::CPU.intel?
      url "https://github.com/grahambrooks/increment/releases/download/v2026.8.0/increment-v2026.8.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8c64458ae4addc06af5545e34029cc7a69af419c7e187e51e38e811c21846109"
    end
  end

  def install
    bin.install "inc"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/inc --version")
    (testpath/"a.txt").write "one\ntwo\n"
    (testpath/"b.txt").write "one\nTWO\n"
    output = shell_output("#{bin}/inc a.txt b.txt", 1)
    assert_match "TWO", output
  end
end
