# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Increment < Formula
  desc "Diff visualizer for the terminal: the aligned side-by-side view"
  homepage "https://github.com/grahambrooks/increment"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.10.1/inc-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "867ac12ad895b98ac89e203bb10629099551633af0e3e0d60af3f392661cd6b0"
    end
    on_intel do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.10.1/inc-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "a68abce11e7f40550d33db660c56b7576d9161ef59c83437c4589d4426782afa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.10.1/inc-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "57c6e7f0cb31949001480d6c2dc3b6c3cf979755cdf48c8dabf6a2bda5dd5fc4"
    end
    on_intel do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.10.1/inc-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8b3201316807c48c68ce0334d0aaba78bfe76dc8629a186288a295ffc9685ec9"
    end
  end

  def install
    bin.install "inc"
  end

  test do
    assert_path_exists bin/"inc"
  end
end
