# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Increment < Formula
  desc "Diff visualizer for the terminal: the aligned side-by-side view"
  homepage "https://github.com/grahambrooks/increment"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.9.2/inc-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "4c8075b0c90fe5389af8fa953d26a7749d142efd5c56ce743f997ec216a75289"
    end
    on_intel do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.9.2/inc-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "834097d29dc4510206bf01a1cbc34076847bae51ce2c271efe65d87c835b8720"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.9.2/inc-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "21a2e9e08271ee69e80e4e778417134fd5a84d06e3fd9423e1bedf3f5ef3be4f"
    end
    on_intel do
      url "https://github.com/grahambrooks/increment/releases/download/v2026.9.2/inc-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "afeef4478530f4f57bbd96c60d43afcfad173e3092fd3bd6e01715e8ef3376bc"
    end
  end

  def install
    bin.install "inc"
  end

  test do
    assert_path_exists bin/"inc"
  end
end
